### ISSUE TITLE
Update a recommendation

### ISSUE THREAD

**Issue by luisdlgarza** [Recommendations-DevOps/recommendations#4]
**As a** user
 **I need** existing recommendations to be updated in the database when new information is given
 **So that** the microservice can give optimal recommendations
   
 ### Details and Assumptions
- Product information can be updated and recommendations need to reflect this
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a new or existing product 
 When the updateRecommendation function is called
 Then the new recommendation will be reflected in the database
 ```

**Comment by annielindahlstern** [comment]
@luisdlgarza I think we should come up with different product labels in grooming, because this feels like a core feature not an enhancement. What do you think?
cc: @galcaspi

**Comment by luisdlgarza** [comment]
@annielindahlstern  Good point. I agree was not sure which label to use. I can make a new "Core" Label
