### ISSUE TITLE
Create function to manually activate recommendations

### ISSUE THREAD

**Issue by cvb2029** [Recommendations-DevOps/recommendations#47]
**As a** marketing manager 
 **I need** to manually activate and deactivate specific recommendations
 **So that** I can operate strategic marketing campaigns that utilize specific recommendations at different times or under different circumstances
   
 ### Details and Assumptions
 * Database exists
 * Recommendations are correctly tagged
 * Recommendations exist in the database
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a specific recommendation exists in the database
 When I activate or deactivate a specific recommendation
 Then the recommendation becomes visible or invisible to users. 
 ```

**Comment by nfa216** [comment]
Decided not to add deactivate function
