### ISSUE TITLE
Add query string support to list function

### ISSUE THREAD

**Issue by cvb2029** [Recommendations-DevOps/recommendations#48]
**As a** user  
 **I need** to perform a text-based search
 **So that** I can find recommendations based on text  
   
 ### Details and Assumptions
 * the specific list being queried includes some string-based data
 * the recommendations microservice has CRUD capabilities
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given string data exists in the table
 When I submit a string-based query
 Then all table results matching the query are returned. 
 ```

**Comment by nfa216** [comment]
From John: Probably the most used query is when the UI of the eCommerce web site wants to display a product page. They probably want to get recommendations for that product. So being able to call GET /recommendations?product_id='xxxxx' is going to be a needed query.
