### ISSUE TITLE
Enable application to fetch database credentials

### ISSUE THREAD

**Issue by cvb2029** [Recommendations-DevOps/recommendations#54]
**As a** developer  
 **I need** my application to fetch database credentials  
 **So that** it will automatically authenticate and save me time. 
   
 ### Details and Assumptions
 *  Modify your application to get the database credentials from the VCAP_SERVICES environment variable if you are using an IBM Cloud database like Cloudant or IBM DB2, or DATABASE_URI if you are using a 3rd party database like PostgreSQL (from ElephantSQL.com). hint: see models.py in lab-bluemix-cf for an example.

   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a queried database requires authentication
 When my application queries the database
 Then it will automatically provide authentication and obtain access. 
 ```

**Comment by annielindahlstern** [comment]
Moving back to In progress to make necessary update to add ElephantSQL and then use ibmcloud cf push to push application to IBM Cloud
@cvb2029  @luisdlgarza @galcaspi @nfa216

**Comment by annielindahlstern** [comment]
Added ElephantSQL, and creating a new ticket for Use ibmcloud cf push to push your application to IBM Cloud. Closing this ticket.
