### ISSUE TITLE
Enable honcho commands with Profile

### ISSUE THREAD

**Issue by cvb2029** [Recommendations-DevOps/recommendations#55]
**As a** developer
 **I need** to utilize honcho commands
 **So that** I can do more stuff more quickly  
   
 ### Details and Assumptions
 * Add honcho to your requirements.txt file and make sure the the command: honcho start works with your Procfile.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a requirements.txt file exists
 When I utilize honcho commands in conjunction with my Procfile
 Then the honcho commands will execute. 
 ```

**Comment by annielindahlstern** [comment]
@galcaspi @luisdlgarza @annielindahlstern @cvb2029 It looks like this is already added to the requirements.txt file

**Comment by annielindahlstern** [comment]
Re-opened this ticket which is why you will see it moving back through the pipeline @cvb2029 and it is now complete and covered by #71 
@galcaspi @luisdlgarza @nfa216
