### ISSUE TITLE
List all recommendations

### ISSUE THREAD

**Issue by cvb2029** [Recommendations-DevOps/recommendations#7]
**As a** user 
 **I need** to see all recommendations
 **So that** I can explore many new products at the same time.  
   
 ### Details and Assumptions
 * Product have recommendation associations
 * Recommendations conform to a standard format
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given multiple recommendations for a shopper exist
 When the shopper visits the recommendations page
 Then the shopper can view all of their recommendations
 ```

**Comment by cvb2029** [comment]
This seems like a secondary function. Are we positive that we can fit this into the next sprint?

**Comment by annielindahlstern** [comment]
PR is #31

**Comment by annielindahlstern** [comment]
Additional PR is #38

@luisdlgarza how do you connect PRs to tickets? :)

**Comment by annielindahlstern** [comment]
@luisdlgarza nevermind - found instructions in the homework PDF!
